### ISSUE TITLE
Thermocouple Daughter Board Design

### ISSUE THREAD

**Issue by clairejhaas** [Cyclone-Racing/CR28_Telem#31]
Create Daughter boards to convert K-type thermocouples to analog signals.
Thermocouples will have the standard two-prong connectors
Controls requested 2

**Comment by APBashara** [comment]
Controls said that they wanted to be able to hook up 2 thermocouples. I think that there are two ways we can approach this: either one thermocouple per board, then we would have 5 boards when we order them, or we can make it sort of like a hub and put 2-4 on each board.

I think that it is a good idea to have extras either way so that we can add more if need be.

**Comment by APBashara** [comment]
Has the parts picked out; just needs to add them into Altium
